### ISSUE TITLE
Validate only data that matches the schema.

### ISSUE THREAD

**Issue by niwinz** [plumatic/schema#120]
Hi!

Would be awesome that schema be able ignore data from validation step that not match any restriction. This is how to works currently:

``` clojure
user => (require '[schema.core :as s])
user => (def schema {:a s/Int :b s/Str})
#'user/schema
user=> (s/validate schema {:a 2 :b "foo"})
{:b "foo", :a 2}
user=> (s/validate schema {:a 2 :b "foo" :d "bar"})
ExceptionInfo Value does not match schema: {:d disallowed-key}  schema.core/validate (core.clj:165)
```

The final step raises validation exception, but the idea is, passing some flag as third parameter that will tells to schema library that it should ignore any additional data that not matches any defined constraint in schema definition from validation step.

Like this:

``` clojure
user=> (s/validate schema {:a 2 :b "foo" :d "bar"} {:strict false})
{:a 2 :b "foo" :d "bar"}
```

As far as I know, currently I can't do this.

**Comment by psalaberria002** [comment]
I am facing the same issue. I want to keep the `disallowed keys`.

@jankronquist Did you figure out a how to setup non strict coercion? 

Adding s/Any to all schemas is an ugly solution.

**Comment by ikitommi** [comment]
[Schema-tools](https://github.com/metosin/schema-tools) has a special matcher for maps, which strips away the keys that are not part of the schema. It can be used for validation, but sadly, it's results can't be used as it strips away the extra keys.

```clj
(require '[schema.core :as s])
(require '[schema-tools.core :as st])

(def schema {:a s/Int :b s/Str})

;; effectively same as validate (just ignore the results)
(st/select-schema {:a 2 :b "foo" :d "bar"} schema)
; {:a 2 :b "foo"}

(st/select-schema {:a "2" :b "foo" :d "bar"} schema)
; ExceptionInfo Could not coerce value to schema: {:a (not (integer? "2"))}  clojure.core/ex-info (core.clj:4617)
```

Idea: we could have a `spec-tools.core/make-open` function that walks the spec and ads the [`s/Any` `s/Any`]  entry if no extra key is present (or - should it override the extra key?)

Also, there should be a `spec-tools.coerce/coercer` with an optional options map with `:open?` option.

```clj
(require '[schema-tools.coerce :as stc])

(def schema {:a s/Int :b s/Str})

((stc/coercer schema (constantly nil) {:open? true})
 {:a 2 :b "foo" :d "bar"})
; {:a 2 :b "foo" :d "bar"}  
```

Actually toyed with this, almost done: https://github.com/metosin/schema-tools/pull/35. I could finish that if @w01fe you think it's the right place to do this (instead of Schema itself).

**Comment by w01fe** [comment]
Sounds good to me, thanks!  (I think my inclination is still that w.r.t to the main Schema library, `open-ness` should be an explicitly declared property of a Schema, not a global configuration option. )

**Comment by ikitommi** [comment]
Great!

Renamed `make-open` to `open-schema` and pushed out `[metosin/schema-tools "0.9.1-SNAPSHOT"]`, where this holds:

```clj
(deftest open-schema-test
  (let [schema {:a Long, :b [(s/maybe {:a Long, s/Keyword s/Keyword})]}
        value {:a 1, :b [{:a 1, "kikka" "kukka"}], "kukka" "kakka"}]
    (is (= {:a Long, :b [(s/maybe {:a Long, s/Any s/Any})], s/Any s/Any}
           (st/open-schema schema)))
    (is (= value ((stc/coercer (st/open-schema schema)) value)))))
```

As we already had the Schema Walker, the actual code was kinda trivial:

```clj
(defn open-schema
  "Walks a schema adding [`s/Any` `s/Any`] entry to all Map Schemas, removing any
  existing extra keys if defined."
  [schema]
  (walk/prewalk
    (fn [x]
      (if (and (map? x) (not (record? x)))
        (assoc (dissoc x (s/find-extra-keys-schema x)) s/Any s/Any)
        x))
```

**Comment by dpsutton** [comment]
This is really helpful. If anyone else ends up here, there are a few caveats:

```clojure
(s/validate {s/Int s/Keyword} {3 :bob}) ;; valid
(s/validate {s/Int s/Keyword} {3 3}) ;; invalid
(s/validate (open-schema {s/Int s/Keyword}) {3 3}) ;; is valid again
```

Seems a fundamental limitation of schema that it has no taxonomy or hierarchy between these generic matchers. So there's no way to schema the notion "integer keys are keywords, keyword keys are integers".

```clojure
(s/validate {s/Int s/Keyword, s/Keyword s/Int} {3 3 :bob 3})
Execution error at schema.core/find-extra-keys-schema (core.clj:782).
More than one non-optional/required key schemata: [Int Keyword]
```

So what happens is if you specify an open map for a schema that requires integer keys to map to something in particular, this is removed from the schema to allow the one (and only one) generic matcher of `s/Any` -> `s/Any`. 

```clojure
(s/validate (open-schema {s/Int s/Keyword}) {3 3})
{3 3}
```
