### ISSUE TITLE
Completers are clojure only

### ISSUE THREAD

**Issue by estsauver** [plumatic/schema#266]
Hey Prismatic, 

It seems like the new completers (which are awesome) are clojure only. It looks like they could be cross compiled to also be cljs compatible. Is there something keeping this Cljs only?

~Earl

**Comment by w01fe** [comment]
Nothing fundamental is preventing making generators and completers cljx, we just ran into an issue with test.check in Clojurescript (I don't recall the details, but think it was probably minor) and wanted to get the release out.  Contributions welcome!

**Comment by estsauver** [comment]
Sounds great, I'll take a look at making a patch. I just wanted to see if I would be stepping on toes. Cheers!

**Comment by w01fe** [comment]
Definitely not -- much appreciated!

**Comment by estsauver** [comment]
Maybe I'm derping something here, but it seems just moving these still has tests passing. I'm not very familiar with the cljx build process, but if you find the failing test case/issue, please let me know and I'll update it.

**Comment by estsauver** [comment]
@w01fe, it looks like there was a change in the closure api here: https://github.com/clojure/test.check/commit/2896000228c473d19e5575c4a97a494718319fb7 that test.check has adapted to. 

Is there a support policy for what versions of clojurescript you all are intending to support?

**Comment by w01fe** [comment]
Thanks for looking into that!  

We don't have an official policy for ClojureScript; for Clojure we actively test on the current and previous major version.  I suppose conservatively supporting cljs versions from the last year seems reasonable, although especially given that this is a new major release we could consider going shorter.  How recent was this change?

It might also be an option to retain compatibility with older versions of cljs, but make completers 1.7+ only or something; I don't know how easy that is with ClojureScript though.

**Comment by estsauver** [comment]
It was 19 days ago (at least from what I can tell.) I don't actually know how I would go about seperating out completers for recent versions of clojurescript with cljx :/  

I'll keep hacking away on this for a sec and put up a PR with a version that at least has working clojurescript support. Given that this was (until a little bit ago) alpha software and clojurescript was still on v0, I would lean towards putting pre 1.7 clojurescript in a maintenance window and move forward. That also gets you off the cljx build pipeline, which is also deprecated (I think?)

**Comment by w01fe** [comment]
Sounds good, thanks for the info.  

For Clojure, you can just have the files there and if they don't compile under old versions or whatever it's fine, so long as you don't `require` them.  I have a feeling this isn't the case for ClojureScript, however. 

I'm not sure 18 days is a long enough compatibility window for us to feel comfortable at this point, but there are definitely other options; ranging from conditional definition, to patching for old versions, to making a completely separate repo / artifact for the time being.  Either way, we aren't ready to get rid of cljx since we want to maintain compatibility with Clojure 1.6 at least until 1.8 comes out.

**Comment by estsauver** [comment]
Sounds good. I'm maintaining a fork currently that has gotten passing tests.

(There's one other thing that came up, it looks like the naming for functions may have changed somewhat. Fn-naming isn't vital for me, so I just changed the tests to reflect the new naming. If you want to see, here's ~ what it looks like.)

https://github.com/estsauver/schema/blob/master/test/cljx/schema/core_test.cljx#L44

I can open a new issue for you for that, but it may make sense to wait until you try to upgrade the development version.

**Comment by w01fe** [comment]
Awesome, thanks.  Once some time passes and we're ready to drop old cljs
support it would be great to merge this stuff back in.

Re: fn-naming, thanks for the heads up -- I think that code will just need
to be updated now that cljs functions have the namespace (which is better
overall anyway).

**Comment by jrheard** [comment]
i can't wait to use completers in cljs. thanks for working on this, guys! :)

**Comment by hugobessaa** [comment]
> Once some time passes and we're ready to drop old cljs support it would be great to merge this stuff back in.

Has time passed enough? Anything I could help to have completers on cljs?

**Comment by w01fe** [comment]
My current thinking is that the best course would be to make generators and completers a separate library `schema-generators`.  That way they can include the dependency on test.check without adding dependencies to schema.core, and they can depend on the latest ClojureScript without affecting compatibility of core.  Thoughts?  

If you'd be willing to help break these out and make them cross-platform, that would be awesome!  Let me know, and I can create a new repo for them.

**Comment by hugobessaa** [comment]
I will grok the current codebase and plan what would be needed. I reply once I do that :)

**Comment by w01fe** [comment]
Awesome, thanks!  I've created a new repo here:

https://github.com/plumatic/schema-generators

So from here, I think it's just a matter of making things work in
ClojureScript.  Since this library is free to target the latest Clojure and
ClojureScript, it will be preferred to use cljc and rip out the cljx
dependencies, but cljx would be fine as well.

Please let me know if you have any questions.  Happy to help however I
can.  Thanks so much for your help with this!

**Comment by milt** [comment]
Hey all, worked on cljs support for the generators lib over the weekend, current tests pass, though there is certainly more to be done.
https://github.com/plumatic/schema-generators/pull/1

**Comment by w01fe** [comment]
Thanks @milt !  I would like to get #321 resolved before doing the official split (since this will cross the generator interface boundaries), but as soon as we get that resolved I'll cut a release, hopefully very soon.

**Comment by w01fe** [comment]
https://github.com/plumatic/schema-generators is out and cross-platform.  Thanks @milt and others for your help, and thanks to everyone else for your patience!

**Comment by hugobessaa** [comment]
Thanks, that's awesome!
