### ISSUE TITLE
Feature idea: schema generation from an XSD

### ISSUE THREAD

**Issue by timur87** [plumatic/schema#307]
Hi,

XSDs are common in the enterprise world and it would be really useful  if we can convert an XSD into a clojure schema.  It would ease reuse of existing schema with Clojure and help its adoption in enterprise. 

Regards,
Timur

**Comment by w01fe** [comment]
Thanks for the request.  I think this is something that would be great for a third-party contrib library -- if you decide to create one, let us know and we can link to it from the README or something.

**Comment by ikitommi** [comment]
@timur87 ping me if you start working with this. We had plans to do same the other-way around - at some time in the far future - to generate XSDs from Schemas. Would help to use clojure with legacy/enterprise systems & tooling (generate XSDs from clojure web apis).

**Comment by timur87** [comment]
@ikitommi , yes I will let you know, when I start with that For the time being, I'm quite busy but it's in my to do list too.

**Comment by w01fe** [comment]
Closing this for now, if you make something we'd love to reference it from the README.  Thanks!
