### ISSUE TITLE
Sequence generators with optional elements don't follow sequence schema semantics

### ISSUE THREAD

**Issue by DalekBaldwin** [plumatic/schema#321]
If a sequence generator declines to generate a value from an optional One schema, it still goes on to try generating values from the remaining subschemas inside the sequence schema, triggering errors from the validator embedded in the generator.

You can verify this by generating values from `FancySeq` as defined in the readme.

**Comment by w01fe** [comment]
Good catch, thanks for the report!   We'll get a fix out as soon as we can.

**Comment by mtruyens** [comment]
As per my request in the newsgroup:

Ideally, it would also be possible to write a Schema for a vector that simply consists of a
repetition of several values. 

For example, a vector that would consist of a succession of first a keyword
and then an integer:

[:a 1, :b 2, :c 3, ...]

Currently, this is not possible without some ugly hacking.

**Comment by w01fe** [comment]
@mtruyens I tried to address your issue in #342 as well, but I couldn't find a way that didn't seriously compromise performance of the existing collections.   My apologies, but I don't think it's likely to happen anytime soon unless someone else figures out a way.  

My current thinking is that the simplest approach for your problem might be to create a new "Transformed" spec that transforms a value going in and out (e.g., `(partial apply hash-map`) and `#(vec (apply concat %))` in your case) and then just use that with map validation to solve your problem.  (Without more thought, I'm not sure we would want to add that to core, though).  

Or if you can figure out how to generalize existing collection specs without compromising performance, that would be even better :)
