### ISSUE TITLE
Schema validation for multimethods?

### ISSUE THREAD

**Issue by favetelinguis** [plumatic/schema#330]
Are there any way to use schema validation on multimethod like th defrecord defn fn macros in schema?

**Comment by favetelinguis** [comment]
Realised it does not rly make sense.

**Comment by w01fe** [comment]
There is `s/defmethod` defined.  We thought about adding `s/defmulti` but it's really complicated to get right, so we've paused on that for now. 

Also, can you please use the mailing list for questions in the future, and keep Github issues for bugs or feature requests?  Thanks!
