### ISSUE TITLE
Nondescriprive Error Message for failing to validate conditional

### ISSUE THREAD

**Issue by JvJ** [plumatic/schema#332]
There's a subtlety of behavior of "conditional" that caused some confusion:

(def CondTest (s/conditional (s/pred even?) s/Int))

(s/validate CondTest 2)
ExceptionInfo Value does not match schema: (throws? (schema.core.Predicate 2))  schema.core/validator/fn--23360 (core.clj:151)

The error messag was almost impossible to understand until I realized that s/conditional takes a raw function as it's predicate argument instead of a (pred ....) schema.  Is there a better way to communicate this in the error messages or documentation for conditional?

**Comment by w01fe** [comment]
Sorry for the confusion, a docstring update and/or assertion in s/conditional would be great.  Thanks for the report.  If you're willing to make a PR, that would be much appreciated as well!
