### ISSUE TITLE
Default for *compile-fn-validation* should come from environment

### ISSUE THREAD

**Issue by hlship** [plumatic/schema#336]
If you come to Schema from the point of view that it is a development and testing tool that should have minimal impact at runtime when in production,  THEN it would be reasonable that there was a way to set *compile-fn-validation* to false before any code that uses s/defn (& etc.) is ever loaded.  

Right now, that takes some gymnastics ... it makes sense to me that the default should come from an environment variable.

I would suggest an environment variable, SCHEMA_COMPILE_FN_VALIDATION be checked, with a default value of true when not present.

**Comment by hlship** [comment]
I can put together a patch if this idea seems reasonable.

**Comment by w01fe** [comment]
If you set `clojure.core/*assert*` to false (which I think can be done from env) fn validation will only be compiled for `:always-validate` functions -- see `schema.macros/compile-fn-validation?`.  I think our assumption was that this would be what most people want. If that's not good for your use case, happy to take a patch -- please just help us understand the use case better first. Thanks!

**Comment by hlship** [comment]
That's a good point, and one I missed!
