### ISSUE TITLE
Validating functions that return lazy sequences forces evaluation

### ISSUE THREAD

**Issue by saulshanabrook** [plumatic/schema#340]
If a function returns a lazy sequence, and we try to validate that function, then all elements of that lazy sequence will also be evaluated.

For example:

```
search.algorithms.base.step-test=> (s/defn hi :- [s/Int] [] (repeat 1))
#'search.algorithms.base.step-test/hi
search.algorithms.base.step-test=> (take 10 (hi))
(1 1 1 1 1 1 1 1 1 1)
search.algorithms.base.step-test=> (s/with-fn-validation (take 10 (hi)))
```
The last line will never finish executing.

I am not sure what the best fix would be here. Obviously it can't validate the type of the items inside a lazy sequence until it is validated.

I would rather have it just not try to validate this at all, and just skip it. Or if it could somehow only validate the items in the sequence that are actually used, that would be ideal.

I stumbled upon this by accident, because in my tests I am using `(use-fixtures :once schema.test/validate-schemas)`.

**Comment by saulshanabrook** [comment]
Would you recommend annotating the function differently if it returns a lazy sequence?

**Comment by saulshanabrook** [comment]
As a workaround I am disabling checking just for that one lazy function call:

```clojure
(ns search.algorithms.base.step-test
  (:require [clojure.test :refer :all]
            [schema.core :as s]
            [schema.test]
            [schema.experimental.generators :as g]

            [search.schemas :as schemas]
            [search.algorithms.base.step :as step]))
(use-fixtures :once schema.test/validate-schemas)

(deftest select-and-tweak->breed-test
  (testing "tweak"
    (let [->individual #(->
                         schemas/Individual
                         g/generate
                         (assoc :id %))
          tweak (fn [_]
                  (cycle
                    [[(->individual "first") (->individual "second")]
                     [(->individual "third") (->individual "fourth")]]))
          select first
          bread (step/select-and-tweak->breed select tweak)
          generation (g/generate schemas/Generation)
          _ (s/set-fn-validation! false) ; validating lazy sequence fails https://github.com/plumatic/schema/issues/340
          next-individuals (bread generation) 
          _ (s/set-fn-validation! true)
          next-ids (map :id next-individuals)]
      (is (= '("first" "second" "third" "fourth") (take 4 next-ids))))))
```

**Comment by w01fe** [comment]
Yes, this is the intended behavior.  There is a bit of context here: https://groups.google.com/forum/#!searchin/prismatic-plumbing/lazy/prismatic-plumbing/tqR0ZnlL-No/d9cdtuxmTCYJ  

Lazily validating would require wrapping the return value, which isn't something we want to get into for a number of reasons.  The simplest option would be to annotate the function as 

`(s/defn ^:never-validate bread ...)`

or you could make a schema that only validates the first n elements or something and use that.  Or if you just want the schema for documentation, I might just do something like:

`(s/defn bread ;- lazy infinite [s/Int])`

(note the semicolon).  Does that make sense?  If you have a good proposal for a lazy seq schema type that isn't confusing and doesn't require wrapping, we would also consider adding that to core.

**Comment by saulshanabrook** [comment]
@w01fe That makes sense, I should have checked the forums first. Thanks for the reply. If I write a partially evaluating schema for infinite sequences, I'll post the code here.

**Comment by w01fe** [comment]
No problem, thanks!
