### ISSUE TITLE
java.lang.NoClassDefFoundError: schema/utils/PSimpleCell

### ISSUE THREAD

**Issue by shriphani** [plumatic/schema#351]
Hi this appears in a project of mine. It is a thin ring server wrapping an internal library. The library has a main so I'm guessing it is AOT compiled.

Any suggestions?

Best,
Shriphani

**Comment by w01fe** [comment]
I think this means you have both an AOT and non-AOT version of Schema running at the same time.  

I have no experience with AOT, but I don't think you want to use a library that's been AOT'd -- I think AOT should be the last thing that's done to your whole project before shipping a jar (if used at all).  

That's about as far as my knowledge goes, however.  If you figure anything out, please let us know what worked.  Thanks!

**Comment by shriphani** [comment]
Yeah that is what I suspected - I'll probably move the main stuff out of the lib and report back. Thanks this is a fantastic lib -

**Comment by w01fe** [comment]
Actually, I think the duplicate thing might cause a different error.  I'm not really sure on this one.  If you can produce a reduced test case, I'm happy to take a look.

**Comment by shriphani** [comment]
Hi that actually solved the problem - I moved the main ns outside and it all worked. Thanks!

**Comment by w01fe** [comment]
Awesome, thanks for following up!

**Comment by sgrove** [comment]
@shriphani I'm running into this as well, and unclear re: the solution. Is there anything more specific you found that triggers this?

**Comment by w01fe** [comment]
Thanks for following up @sgrove  -- for any other watchers, conversation is continued in #354
