### ISSUE TITLE
validate slow when there's an error

### ISSUE THREAD

**Issue by sonwh98** [plumatic/schema#352]
```
(def KoalaState {:company-name s/Str
                           :logged-in s/Bool})

(s/validate KoalaState {:company-name "koala" :logged-in "false"})
```
validate returns immediately when the type matches. However, if it doesn't match like the above, it takes a 20 seconds to return the error message. Is this normal?

validate returns quickly when there's an error in Clojure. The slowness is only in ClojureScript

**Comment by w01fe** [comment]
First I've heard about this.  My guess is it's something to do with your environment and how it handles errors, rather than anything to do with schema.  What happens if you just throw an exception rather than calling `s/validate`?

**Comment by sonwh98** [comment]
oh you're right. I was testing it in the boot.cljs clojurescript repl. (js/throw "foo") also takes a long time
