### ISSUE TITLE
Character schema missing

### ISSUE THREAD

**Issue by bernardosamorim** [plumatic/schema#361]
Is there a reason for a Char schema not being defined in schema.core? 
Do you guys think it would be a good addition?

If so, I'd like to work on it.

Best regards

**Comment by w01fe** [comment]
Both `Character` and `char` should work -- can you provide an example of what's not working for you?

https://github.com/plumatic/schema/blob/master/src/cljx/schema/core.cljx#L221

Thanks!

**Comment by bernardosamorim** [comment]
Oh, I hadn't seen it. But why is there no pred defined for it?

Thanks!

**Comment by w01fe** [comment]
What do you mean?

**Comment by w01fe** [comment]
If you still think there's an issue, please clarify and reopen.  Otherwise, if you have further questions please ask on the mailing list.  Thanks!
