### ISSUE TITLE
isa schema not working correctly for keywords without hierarchy

### ISSUE THREAD

**Issue by camsaul** [plumatic/schema#369]
Not sure if I'm using this wrong, but it's not working as I'd expect.

```clojure
(derive :type/Integer :type/Number) 
;; -> nil

(isa? :type/Integer :type/Number)
;; -> true

(s/validate (s/isa :type/Number) :type/Integer)
;; -> ExceptionInfo Value does not match schema: (throws? (isa? :type/Integer :type/Number))  schema.core/validator/fn--8446 (core.clj:155)
```

I can work around it using `pred`, so it's not a deal-breaker.

```clojure
(s/validate (s/pred #(isa? % :type/Number)) :type/Integer) 
;; -> :type/Integer
```

**Comment by w01fe** [comment]
Yes, seems like this is a problem with `isa` and the default hierarchy --
thanks for the report.  Since `global-hierarchy` is private, I guess the
best solution is probably to avoid referencing it and passing the
precondition directly into Isa.  PR welcome!

**Comment by camsaul** [comment]
Makes sense. I'll submit a PR for this later today when I get a chance

**Comment by w01fe** [comment]
Great, thanks!
