### ISSUE TITLE
Cannot merge conditionals

### ISSUE THREAD

**Issue by JustinC474** [plumatic/schema#375]
I'm trying to write a schema that merges two conditionals like so:

```clojure
(def foo
  (merge
    (s/if #(:foo %)
      {:foo s/Str}
      {:foo (s/eq nil)})
    (s/if #(:bar %)
      {:bar s/Str}
      {:bar (s/eq nil)})))
```

However, it seems that once I load this it only keeps the second `(s/if ...` and does away with the first

```
circle-migrator.core=> (def foo (merge (s/if #(:foo %) {:foo s/Str} {:foo (s/eq nil)}) (s/if #(:bar %) {:bar s/Str} {:bar (s/eq nil)})))
#'circle-migrator.core/foo
circle-migrator.core=> foo
(conditional circle-migrator.core/fn--13324 {:bar Str} clojure.core$constantly/fn--4614 {:bar (eq nil)})
circle-migrator.core=>
```

I tried to reduce the complexity a bit by removing the second `(s/if ...`

```
circle-migrator.core=> (def foo (merge (s/if #(:foo %) {:foo s/Str} {:foo (s/eq nil)}) {:bar s/Str}))
#'circle-migrator.core/foo
circle-migrator.core=> foo
(conditional circle-migrator.core/fn--13327 {:foo Str} clojure.core$constantly/fn--4614 {:foo (eq nil)})
circle-migrator.core=> (s/validate foo {:foo "foo" :bar "bar"})

ExceptionInfo Value does not match schema: {:bar disallowed-key}  schema.core/validator/fn--622 (core.clj:155)
circle-migrator.core=>
```

So it seems like conditionals cannot be merged once the conditional has resolved. This seems like unintuitive behavior (at least to me). Is this a bug or is it on purpose?

**Comment by w01fe** [comment]
If returns a conditional schema, which is a record that implements the
schema protocol and contains a list of conditions and subschemas inside.
Merge merges the keys of the record, which is not what you want.

If you look at the implementation of conditional schema you should be able
to see how to properly merge what's inside.  I'm on my phone but can
provide details later if you can't figure it out.

**Comment by w01fe** [comment]
To elaborate, this is the definition of the conditional record:

https://github.com/plumatic/schema/blob/master/src/cljx/schema/core.cljx#L477

and preds-and-schemas is a sequence of [predicate, schema] pairs, so you
can delve into there to merge your map with the containing schemas.

**Comment by JustinC474** [comment]
I ended up solving it with...

```clojure
(def foo
    (s/conditional
      #(and (:foo %) (bar %))
        (merge {:foo s/Str} {:bar s/Str})
      ...```

for each of the 4 possible combinations, which I think is what you were suggesting.

**Comment by w01fe** [comment]
Great, that will work too.  Thanks for following up!
