### ISSUE TITLE
Using generators to generate data.

### ISSUE THREAD

**Issue by dhruv-dave** [plumatic/schema#378]
This is a QUESTION regarding generators.

Hey, I really like the schema library and frequently use it just to try it out and get familiar with it.

I am running into a bit of a problem while trying to generate data given a specific schema.
Here is an example:

I have a schema for alarms. Some service doesn't work, it generates "alarms". For testing purposes i would like to generate thousands of alarms.
Here is a small alarms schema:

(def alarms
{:alarm-type s/Str
 :cause s/Str})

Now the alarm-type can only be one of types "Critical", "Major", or "Minor".
For this example, lets say the cause also has to be one of ""Power Off", "Reset", "System Failure", "No Idea!".

How do i generate 200 alarms based on these requirements?

`(generators/sample
 20 Violations
 {s/Str (check-generators/elements ["Critical" "Major" "Minor"])})`

=>> 
`({:alarm-type "Critical", :cause "Minor"}
 {:alarm-type "Critical", :cause "Minor"}
 {:alarm-type "Major", :cause "Critical"}
 {:alarm-type "Critical", :cause "Major"}
 {:alarm-type "Major", :cause "Minor"}
 {:alarm-type "Critical", :cause "Critical"}
 {:alarm-type "Minor", :cause "Major"}
 {:alarm-type "Minor", :cause "Major"}
 {:alarm-type "Minor", :cause "Critical"}
 {:alarm-type "Minor", :cause "Critical"})`

As you can see, by using the arguments `{s/Str (check-generators/elements ["Critical" "Major" "Minor"])}` i overwrite both the :alarm-type and :cause.

Using this code:
`(clojure.pprint/pprint (generators/sample
                        10 Violations
                        {s/Str (check-generators/elements ["Critical" "Major" "Minor"])}
                        {s/Str (check-generators/elements ["Power Off" "reset" "System failure" "I don't know"])}))`

I get the following error:
`1. Unhandled java.lang.ClassCastException
   clojure.test.check.generators.Generator cannot be cast to
   clojure.lang.IFn

            generators.clj:  203  schema.experimental.generators/eval22604/generator/fn/gen
            generators.clj:   32  schema.experimental.generators/sub-generator/fn
                  core.clj:   81  schema.spec.core/with-cache
                  core.clj:   75  schema.spec.core/with-cache
            generators.clj:   30  schema.experimental.generators/sub-generator
            generators.clj:   27  schema.experimental.generators/sub-generator
            generators.clj:   50  schema.experimental.generators/element-generator
            generators.clj:   39  schema.experimental.generators/element-generator
            generators.clj:   54  schema.experimental.generators/elements-generator/fn`

Any help would be awesome!
Thanks.

**Comment by w01fe** [comment]
Hi, thanks for the kind words! 

You need alarm-type and cause to have their own schemas, not just s/Str.  Best would be to do 

```clojure
(def alarms
  {:alarm-type (s/enum "Critical" "Major" "Minor")
    :cause (s/enum "Power Off" "Reset" "System Failure" "No Idea!")})
```

and you'll get better validation generation plus generation will work out of the box.  

If you don't want to do that for whatever reason, you can do something like
 
```clojure
(s/defn AlarmType (s/named s/Str "alarm"))
(s/defn Cause (s/named s/Str "cause"))
```

and use these both in your Schema for Alarms and in as the keys in the map you pass to `generators/sample`.

Hope this helps -- let me know if you have questions.  (FWIW, I would also recommend looking into `clojure.spec`, since I think once released it will become the community standard for doing this sort of stuff).
