### ISSUE TITLE
How do I pass the entire validate candidate as parameter to pred?

### ISSUE THREAD

**Issue by zacyang** [plumatic/schema#379]
Hi
I am working on a validator, for some fields it require the context from the validate root candidate, for instance.

I want to verify the uri in the map. But it require the parameters (in this case, the value **"value"** in key **:other-key-require**) define in other section of the map in fn **uri-parameter-is-defined?**.

The following is the sudo code to demostrate what I mean:

`
(defn uri? [root i]
`
 `
(uri-parameter-is-defined? root i)
)
`
`
(def my_schema
{
(s/required-key :baseUri)       (s/pred uri?)
})
`

`
(def root {:other-key-require "value" :baseUri "http://{value}/subdomain/"}
`
`
(s/validate my_schema root)
`

I found normally for the pred-fn can only accept one parameter, question is , is there a way I can pass in the root to the uri? fn to check some value accordingly?

**Comment by w01fe** [comment]
Schemas are context-free, so there is no way to access root from the
baseuri validator. Instead, you should attach this consistency condition to
my_schema using s/constrained.

In the future, we would also appreciate it if you ask questions on the
schema mailing list rather than using GitHub issues. Thanks!

**Comment by zacyang** [comment]
My apologies to my carelessness, I should have raised this in the mail ist instead of issue list, which I failed to discovery in the first place. Please close this issue, 
Many thanks.

Also **constrained** will not solve the problem that in case a given validation dependent on a context. I will add a special case in the validation to bypass this issue.

Thanks for your quick response.

**Comment by w01fe** [comment]
No worries, just a request for next time.  

Why won't `constrained` solve your issue?  Would something like this do what you want?

```clojure
(def my_schema 
  (s/constrained { (s/required-key :baseUri) (s/pred uri?) }
     (fn uri-matches-other? [m] (.startsWith ^String (:baseUri m) (str "http://" (:other-key-require m)))))))

```
