### ISSUE TITLE
website css should be server under https

### ISSUE THREAD

**Issue by jaimeagudo** [plumatic/schema#381]
The site ('https://plumatic.github.io) looks awkward because of this, just open an incognito browser tab and check the console

```Mixed Content: The page at 'https://plumatic.github.io//' was loaded over HTTPS, but requested an insecure stylesheet 'http://plumatic.github.io//css/main.css'. This request has been blocked; the content must be served over HTTPS.```

**Comment by w01fe** [comment]
Thanks for the heads up!  Should be fixed now, let me know if you're still seeing issues.
