### ISSUE TITLE
seq enum

### ISSUE THREAD

**Issue by fl00r** [plumatic/schema#382]
Hi!

What if I have a set/list/vector of some values which I want to pass to `enum`.

Now I have to use `apply` like this `(apply s/enum #{:a :b :c})`, right?

Even though it is not very verbose I would expect a little bit of sugar for this case.

For example `enum-seq`

```clojure
(clojure.core/defn enum-seq
  "A value that must be = to some element of vs."
  [vs]
  (apply enum vs))
```

**Comment by w01fe** [comment]
Yes, you need to call `apply`.  I don't think it's worthy of sugar though.  For instance, there is no `max-seq` function in `clojure.core`.

**Comment by fl00r** [comment]
Ok, I see, thank you!
