### ISSUE TITLE
Compilation warning with clojurescript 1.9.542

### ISSUE THREAD

**Issue by Kauko** [plumatic/schema#392]
Compilation warning when using Clojurescript 1.9.542 and Schema 1.1.5
```
WARNING: ->MapEntry already refers to: cljs.core/->MapEntry being replaced by: schema.core/->MapEntry at line 759 dev-resources/js/out/schema/core.cljs
```
This has been reported to [Google groups](https://groups.google.com/d/msg/clojure/In88wV63QyE/5daVkzxzBgAJ) and to [Slack](https://clojurians.slack.com/archives/C03S1L9DN/p1494826583789744)

**Comment by w01fe** [comment]
Thanks for the report.  I guess we just need to add an exclusion to the namespace.  PR welcome!
