### ISSUE TITLE
Colorized output for schema violations breaks xml test reporting

### ISSUE THREAD

**Issue by MichaelBlume** [plumatic/schema#394]
- [x] This is a bug report (with instructions to reproduce) or other issue with the code
(if this is a question or feature request, please **do not** open an issue and post on the [mailing list](https://groups.google.com/forum/#!forum/prismatic-plumbing) instead).  

We run our tests with test2junit and consume the resulting xml files with jenkins. When we run tests which induce schema violations, the yellow coloring of the printed output turns into special characters in the generated xml, which trips up jenkins.

Possibly schema could check whether its output stream is a tty and only colorize if it is?

Honestly not quite sure if this is something that should be fixed in schema or in test2junit, have also filed ruedigergad/test2junit#12

**Comment by w01fe** [comment]
I don't have a good sense either.  Let us know what test2junit says and let's take things from there. If they don't think it's a bug on their end, happy to talk about how to fix it here. Thanks!
