### ISSUE TITLE
Schema uses a conflicting name with latest ClojureScript core

### ISSUE THREAD

**Issue by yogthos** [plumatic/schema#397]
- [ ] This is a bug report (with instructions to reproduce) or other issue with the code
(if this is a question or feature request, please **do not** open an issue and post on the [mailing list](https://groups.google.com/forum/#!forum/prismatic-plumbing) instead).

Using the latest version of ClojureScript `1.9.660` add Schema to the project and compile ClojureScript. The following error will be produced:

```
->MapEntry already refers to: cljs.core/->MapEntry being replaced by: schema.core/->MapEntry at line 751 target/cljsbuild/public/js/out/schema/core.cljsx
```

**Comment by w01fe** [comment]
Is this with the latest version of schema?  https://github.com/plumatic/schema/pull/393

**Comment by yogthos** [comment]
Ah my apologies, I did have an older version of Schema in the project.

**Comment by w01fe** [comment]
No worries .
