### ISSUE TITLE
Use goog.object/get/set instead of aget/aset

### ISSUE THREAD

**Issue by danielcompton** [plumatic/schema#404]
- [x] This is a bug report (with instructions to reproduce) or other issue with the code
(if this is a question or feature request, please **do not** open an issue and post on the [mailing list](https://groups.google.com/forum/#!forum/prismatic-plumbing) instead).  

ClojureScript now warns on the use of `aget`/`aset` with non-integer indexes. I think this code should move to using `goog.object/get` and `set` instead?

https://github.com/plumatic/schema/blob/1b968f95b94f92c0124a4e7f45472417215fcd21/src/cljx/schema/utils.cljx#L157-L161

More info: https://clojurescript.org/news/2017-07-14-checked-array-access

**Comment by w01fe** [comment]
Sounds right to me, thanks for the report!  (PR welcome!)

**Comment by w01fe** [comment]
Let me know if this is / starts being actively annoying and I can cut a release.  Thanks again for the report.
