### ISSUE TITLE
clojure spec It seems to be a mistake. schema is Right direction

### ISSUE THREAD

**Issue by xingzhefeng** [plumatic/schema#408]
clojure spec It seems to be a mistake. schema is Right direction

**Comment by w01fe** [comment]
I am thankful for your appreciation of schema, but we ask that you use Github issues on this project only for bug reports (as requested in the template). 

If you have constructive thoughts to share (in the spirit of https://clojure.org/community/etiquette) may I suggest you add them over on the mailing list, perhaps on this thread: https://groups.google.com/d/msg/prismatic-plumbing/Us4JAFDZ2no/-A-J8ulfAQAJ .
