### ISSUE TITLE
cjlx has been deprecated

### ISSUE THREAD

**Issue by baldurmen** [plumatic/schema#425]
Hi!

I'm working on packaging this program in Debian and it seems `schema` still depends on [cljx](https://github.com/lynaghk/cljx), that has been deprecated since at least 2016...

Are there any plans to move away from it and use `.cljc` instead? From a packaging point, it would be very helpful, as packaging deprecated software ain't great :( 

Thanks for working on `schema` !!

**Comment by w01fe** [comment]
No concrete plans as far as I know, but contributions are welcome.
