### ISSUE TITLE
Missing field "applicantLocationRequirements

### ISSUE THREAD

**Issue by abhi28091989** [plumatic/schema#447]
I am using WordPress Plugin [https://wordpress.org/plugins/job-postings/](url)
I got an Error in google search result Job posting 

> Missing field "applicantLocationRequirements"

Please find SS Here: [https://snipboard.io/5soeRx.jpg](url)
[https://snipboard.io/D6Susx.jpg](url)

I have coding exist in my plugin for "applicantLocationRequirements" field
` 
                        if( $remote == 'on' && $remote_data ){
                            $remote_data = unserialize($remote_data);

                            if( count($remote_data) >= 1 && $remote_data[0]['type'] != '' && $remote_data[0]['name'] != '' ){

                                if(count($remote_data) == 1){
                                    self::$json_ld['applicantLocationRequirements'] = json_decode(json_encode(array('@type' => $remote_data[0]['type'], 'name' => $remote_data[0]['name'])), FALSE);
                                }else{
                                    $data_array = array();
                                    foreach($remote_data as $data){
                                        $data_array[] = array('@type' => $data['type'], 'name' => $data['name']);
                                    }
                                    self::$json_ld['applicantLocationRequirements'] = json_decode(json_encode($data_array), FALSE);
                                }
                            }
                        }

                        if( $remote == 'on' ){
                            self::$json_ld['jobLocationType'] = "TELECOMMUTE";
                        }`
Please Suggest me Something i am really Fadeup  with that.

**Comment by w01fe** [comment]
From your cross-posting here https://github.com/schemaorg/schemaorg/issues/3161 I will assume this is not actually relevant to this library, closing unless you can provide more details and explanation.
