### ISSUE TITLE
Converting ValidationErrors to user friendly messages

### ISSUE THREAD

**Issue by symfrog** [plumatic/schema#56]
I am new to schema, is an intended use case for schema to validate user input? 

If so, what is the idiomatic way to map ValidationErrors to user friendly error messages?

**Comment by vincentjames501** [comment]
As someone who just started using schema less than an hour ago. I too ran into this. It would be nice to add a way to transform these errors into something the end user can consume. It would also be nice to support things like localization.

**Comment by rauhs** [comment]
Just for other people who end up here. I just wrote this (used core.match to match errors and turn them into user-presentable strings):

https://gist.github.com/rauhs/cfdb55a8314e0d3f4862

But I also just found this:
https://github.com/cddr/integrity

May it help future googlers.

**Comment by limist** [comment]
@rauhs  :+1: Very helpful gist code, thank you!  `integrity` looks interesting too, but your gist code is more straightforward.

**Comment by kendagriff** [comment]
@rauhs @symfrog Thanks for the great ideas.
