### ISSUE TITLE
nested vectors not validating

### ISSUE THREAD

**Issue by shaunxcode** [plumatic/schema#61]
This works: 

```
(s/validate [(s/one s/Int :some-int) [s/Int]] [4 [3 2]])
```

The following does not:

```
(s/validate [[s/Int] (s/one s/Int :some-int)] [[4 3] 2])
```

I receive: "RuntimeException Sequence schema [[Int] #schema.core.One{:schema Int, :optional? false, :name :some-int}] does not match [one\* optional\* rest-schema?]  schema.core/parse-sequence-schema (core.clj:746)"

**Comment by moonranger** [comment]
Sorry to comment on a old issue, but i get the same error when trying to model the GeoJSON format http://geojson.org/geojson-spec.html

I wrote the following schema which could not work:

```clojure
(s/defschema GeoJSON
  {:type String
   :features [{:type String
               :geometry {:type (s/enum "Point"
                                        "MultiPoint"
                                        "LineString"
                                        "MultiLineString"
                                        "Polygon")
                          :coordinates (s/either [Double Double]
                                                 [[Double Double]]
                                                 [[[Double Double]]])}
               :properties {s/Any s/Any}}]})
```

Refer to the GeoJSON spec for all the cases of coordinates.

**Comment by w01fe** [comment]
`[Double Double]` is not a valid schema.  You can do `[Double]` for a sequence of doubles, or `[(s/one Double 'lon) (s/one Double 'lat)]` or `(s/pair Double 'lon Double 'lat)` for pair.
